version: '3'
services:
  web:
    image: nginx
    ports:
      - "8888:8888"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  weba:
    image: nginx
    volumes:
      - ./nginx-a/nginx.conf:/etc/nginx/nginx.conf

  webb:
    image: nginx
    volumes:
      - ./nginx-b/nginx.conf:/etc/nginx/nginx.conf