version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/sites/bootstrap
      - ./src/downloads:/sites/downloads